### ISSUE TITLE
[BUG] - Fine is not showing up

### ISSUE THREAD

**Issue by Karl-Taken** [CloudTheWolf/legacy-mdt-issue-tracker#6]
**Summary:**
When putting all the tickets for the suspect. It does not add up all the fines and show it.

**Steps to Reproduce:**
- Create an Incident
- Add a suspect
- Add a ticket

**Expected Results:**
It should add up the total fine for all the tickets but it only adds up t
he points.

**Actual Results:**
It only adds up the points and not the fine
![image](https://github.com/CloudTheWolf/legacy-mdt-issue-tracker/assets/67985497/f7c72ba3-e3f9-453a-8110-f46ac754cc73)

**Comment by CloudTheWolf** [comment]
@Discordop This is because of the Incident Type selected. A Citation will not issue a fine, but will add points on their licence
