### ISSUE TITLE
[BUG] - Not all incidents are showing up

### ISSUE THREAD

**Issue by Karl-Taken** [CloudTheWolf/legacy-mdt-issue-tracker#7]
**Summary:**
The list of incident does not go far down causing some incidents now to show up. In order to see the older incidents, you'll have to search for the incident name.

**Steps to Reproduce:**
Go to incident tab and scroll all the way down. It will not show all the incidents that exists if you have a lot

**Expected Results:**
It should show all the existing incidents

**Actual Results:**
Only shows some incidents.

**Comment by CloudTheWolf** [comment]
This is by design to reduce load time and server load. 
Users should instead search for incidents when it is not in the "Recent Incidents" list
